// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAgent(arg1) {
  return window['go']['main']['App']['AddAgent'](arg1);
}

export function AddMCP(arg1) {
  return window['go']['main']['App']['AddMCP'](arg1);
}

export function CheckSkillUpdates() {
  return window['go']['main']['App']['CheckSkillUpdates']();
}

export function CreatePrompt(arg1, arg2) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function ImportSkill(arg1, arg2) {
  return window['go']['main']['App']['ImportSkill'](arg1, arg2);
}

export function InstallSkills(arg1, arg2) {
  return window['go']['main']['App']['InstallSkills'](arg1, arg2);
}

export function PreviewSkills(arg1) {
  return window['go']['main']['App']['PreviewSkills'](arg1);
}

export function ReadPrompt(arg1) {
  return window['go']['main']['App']['ReadPrompt'](arg1);
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function RemoveSkill(arg1) {
  return window['go']['main']['App']['RemoveSkill'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function TestMCP(arg1) {
  return window['go']['main']['App']['TestMCP'](arg1);
}

export function ToggleAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleAgent'](arg1, arg2, arg3);
}

export function ToggleMCP(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleMCP'](arg1, arg2, arg3);
}

export function TogglePrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['TogglePrompt'](arg1, arg2, arg3);
}

export function ToggleSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleSkill'](arg1, arg2, arg3);
}

export function UpdateHostPaths(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateHostPaths'](arg1, arg2, arg3, arg4);
}

export function UpdatePrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePrompt'](arg1, arg2, arg3);
}

export function UpdateSkill(arg1) {
  return window['go']['main']['App']['UpdateSkill'](arg1);
}
