// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAgent(arg1:main.AgentInput):Promise<main.Snapshot>;

export function AddMCP(arg1:main.MCPInput):Promise<main.Snapshot>;

export function GetSnapshot():Promise<main.Snapshot>;

export function ImportSkill(arg1:string,arg2:string):Promise<main.Snapshot>;

export function InstallSkill(arg1:string,arg2:string,arg3:string):Promise<main.Snapshot>;

export function Refresh():Promise<main.Snapshot>;

export function RestoreBackup(arg1:string):Promise<main.Snapshot>;

export function TestMCP(arg1:string):Promise<string>;

export function ToggleAgent(arg1:string,arg2:string,arg3:boolean):Promise<main.Snapshot>;

export function ToggleMCP(arg1:string,arg2:string,arg3:boolean):Promise<main.Snapshot>;

export function ToggleSkill(arg1:string,arg2:string,arg3:boolean):Promise<main.Snapshot>;

export function UpdateHostPaths(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Snapshot>;
